import assert from 'node:assert/strict';
import {renderToString} from 'react-dom/server';
import {ComponentPreview} from '../components/component-preview';
import {TooltipProvider} from '../components/ui/tooltip';
import {Toaster} from '../components/ui/toast';
import {catalog,initialScreen} from '../lib/catalog';
import {buildQuestions,parseAnswers,validateScreen,demoCompose,ENDPOINT,MODEL} from '../lib/decisions';
import {POST} from '../app/api/compose/route';
const questions=buildQuestions();
assert.equal(catalog.length,64);
assert.equal(new Set(catalog.map(c=>c.id)).size,64);
assert.equal(Object.keys(questions).length,69);
for(const c of catalog){const html=renderToString(<TooltipProvider><Toaster><ComponentPreview id={c.id}/></Toaster></TooltipProvider>);assert.ok(html.length>0,`${c.id} renders`);}
console.log('64 component previews render with their required providers.');
const answers=Object.fromEntries(Object.entries(questions).map(([id,q])=>[id,{type:'choice',choice:id.startsWith('component_')?'hidden':Object.keys(q.criteria)[0]}]));
answers.component_table.choice='first';answers.component_chart.choice='last';
const parsed=parseAnswers({answers});assert.deepEqual(parsed.screen.components,['table','chart']);validateScreen(parsed.screen);
assert.throws(()=>parseAnswers({answers:{...answers,layout:{choice:'arbitrary-code'}}}));
assert.throws(()=>parseAnswers({answers:{layout:{choice:'grid'}}}));
assert.throws(()=>validateScreen({...initialScreen,components:['unknown']}));
assert.throws(()=>validateScreen({...initialScreen,components:['card','card']}));
assert.deepEqual(demoCompose('make it dark and compact',initialScreen),{...initialScreen,theme:'dark',density:'compact'});
assert.equal(demoCompose('show all components').components.length,64);
const request=(body:unknown,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/compose',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
const oldKey=process.env.OPENROUTER_API_KEY;delete process.env.OPENROUTER_API_KEY;
assert.equal((await POST(request({prompt:'hello',current:initialScreen}))).status,401);
assert.equal((await POST(request({prompt:'hello',current:initialScreen},'https://untrusted.example'))).status,403);
assert.equal((await POST(request({prompt:'x'.repeat(2001),current:initialScreen}))).status,400);
assert.equal((await POST(request({prompt:'hi',current:{}}))).status,400);
assert.equal((await POST(request(null))).status,400);
assert.equal((await POST(new Request('http://localhost:3000/api/compose',{method:'POST',body:'{'}))).status,400);
let calls=0;const realFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,ENDPOINT);assert.equal(new Headers(options?.headers).get('Authorization'),'Bearer test-key');assert.equal(typeof options?.body,'string');const payload=JSON.parse(options?.body as string);assert.equal(payload.model,MODEL);assert.equal(Object.keys(payload.questions).length,69);return Response.json({answers});};
const success=await POST(request({prompt:'a sales overview',current:initialScreen,apiKey:'test-key'}));assert.equal(success.status,200);const payload=await success.json() as {screen:unknown};assert.deepEqual(validateScreen(payload.screen).components,['table','chart']);assert.equal(calls,1);
globalThis.fetch=async()=>Response.json({error:'upstream secret'}, {status:402});const failure=await POST(request({prompt:'hello',current:initialScreen,apiKey:'test-key'}));assert.equal(failure.status,502);assert.ok(!(await failure.text()).includes('upstream secret'));
globalThis.fetch=async()=>Response.json({answers:{}});assert.equal((await POST(request({prompt:'hello',current:initialScreen,apiKey:'test-key'}))).status,502);
globalThis.fetch=realFetch;if(oldKey!==undefined)process.env.OPENROUTER_API_KEY=oldKey;
console.log('Decision ordering, malformed outputs, prompt limits, missing keys, origin checks, upstream failures, and successful API mapping pass.');
